### ISSUE TITLE
Detailed affiliation information

### ISSUE THREAD

**Issue by ericjeangirard** [miku/dcdump#1]
Hello

It could be nice to dump all the informations available, included detailed affiliations. According to https://support.datacite.org/docs/can-i-see-more-detailed-affiliation-information-in-the-rest-api
an extra parameter `affiliation=true` should be passed in the URL.
What do you think ?

**Comment by miku** [comment]
Good point! I added the parameter by default - it's in [v0.1.3](https://github.com/miku/dcdump/releases/tag/v0.1.3).

**Comment by ericjeangirard** [comment]
Thanks a lot!
